### ISSUE TITLE
How to run the script

### ISSUE THREAD

**Issue by eam23** [mzmaili/AzurePRTLoginReport#2]
Hello, 

This is not a issue, I want to run the script, but I don't know how, i understood all the step, until run de Script, 
Could you please send me and example run?

**Comment by mzmaili** [comment]
Please check the mentioned examples that describe how to run the script. I am also sharing them here:

.EXAMPLE 
    .\AzurePRTLoginReport.ps1 
    Search for the TXT files that hold the user login information, analyse them and then, generates CSV report. 
 
.EXAMPLE 
    .\AzurePRTLoginReport.ps1 -SourceFolder "\\FileServer\UsersLogs" -OutputFolder "\\SharedFolder\AzurePRTLoginReport" 
    Search for the TXT files that hold the user login information in the entered folder, analyse them and then, export CSV report to the entered shared folder location. 
 
.EXAMPLE 
    .\AzurePRTLoginReport.ps1 -ExcelReport 
        Search for the TXT files that hold the user login information, analyse them and then, generates Excel report.
